// Catalogo de productos para mostrar en la pagina.
export const products = [
  {
    id: "auricular-bt-a1",
    name: "Auriculares Bluetooth A1",
    category: "audio",
    categoryLabel: "Audio",
    price: 185000,
    image: "/images/auriculares.webp",
    description: "Sonido envolvente, almohadillas comodas y bateria para acompanarte todo el dia.",
    whatsappMessage: "Hola, quiero consultar por los Auriculares Bluetooth A1.",
    specs: ["Conexion Bluetooth 5.3", "Microfono integrado", "Hasta 30 horas de bateria"],
  },
  {
    id: "samsung-galaxy-a55",
    name: "Samsung Galaxy A55 5G",
    category: "celulares",
    categoryLabel: "Celulares",
    price: 2890000,
    image: "/images/samsung-galaxy-a55.jpg",
    description: "Celular 5G con pantalla AMOLED fluida, camara nitida y diseno resistente.",
    whatsappMessage: "Hola, quiero consultar por el Samsung Galaxy A55 5G.",
    specs: ["Pantalla Super AMOLED 120 Hz", "Camara principal 50 MP", "128 GB de almacenamiento"],
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    category: "celulares",
    categoryLabel: "Celulares",
    price: 5890000,
    image: "/images/iphone-15.jpg",
    description: "Rendimiento premium, camara avanzada y carga USB-C en un formato elegante.",
    whatsappMessage: "Hola, quiero consultar por el iPhone 15.",
    specs: ["Chip A16 Bionic", "Camara dual", "Pantalla Super Retina XDR"],
  },
  {
    id: "redmi-13",
    name: "Xiaomi Redmi 13",
    category: "celulares",
    categoryLabel: "Celulares",
    price: 1590000,
    image: "/images/redmi-13.jpg",
    description: "Gran pantalla, bateria duradera y excelente relacion precio-rendimiento.",
    whatsappMessage: "Hola, quiero consultar por el Xiaomi Redmi 13.",
    specs: ["Pantalla AMOLED", "Bateria 5000 mAh", "Carga rapida"],
  },
  {
    id: "smartwatch-s1",
    name: "Smartwatch S1",
    category: "wearables",
    categoryLabel: "Wearables",
    price: 249000,
    image: "/images/smartwatch.webp",
    description: "Monitorea tu actividad, revisa notificaciones y controla tu rutina desde la muneca.",
    whatsappMessage: "Hola, quiero consultar por el Smartwatch S1.",
    specs: ["Pantalla tactil", "Registro de actividad", "Notificaciones del telefono", "Resistente al agua"],
  },
  {
    id: "hp-pavilion-15",
    name: "HP Pavilion 15",
    category: "computacion",
    categoryLabel: "Computacion",
    price: 4550000,
    image: "/images/hp-pavilion-15.jpg",
    description: "Notebook versatil para oficina, clases, videollamadas y tareas exigentes.",
    whatsappMessage: "Hola, quiero consultar por la HP Pavilion 15.",
    specs: ["Intel Core i5", "SSD 512 GB", "Pantalla 15.6 pulgadas"],
  },
  {
    id: "lenovo-ideapad-3",
    name: "Lenovo IdeaPad 3",
    category: "computacion",
    categoryLabel: "Computacion",
    price: 3890000,
    image: "/images/lenovo-ideapad-3.jpg",
    description: "Equipo confiable para estudiar, trabajar y navegar con buena autonomia.",
    whatsappMessage: "Hola, quiero consultar por la Lenovo IdeaPad 3.",
    specs: ["AMD Ryzen 5", "8 GB RAM", "SSD 256 GB"],
  },
  {
    id: "macbook-air-m2",
    name: "MacBook Air M2",
    category: "computacion",
    categoryLabel: "Computacion",
    price: 8790000,
    image: "/images/macbook-air-m2.jpg",
    description: "Portatil ultraligera con rendimiento silencioso y bateria de larga duracion.",
    whatsappMessage: "Hola, quiero consultar por la MacBook Air M2.",
    specs: ["Chip Apple M2", "Pantalla Liquid Retina", "Diseno ultradelgado"],
  },
  {
    id: "teclado-mecanico-k2",
    name: "Teclado Mecanico K2",
    category: "perifericos",
    categoryLabel: "Perifericos",
    price: 295000,
    image: "/images/teclado.webp",
    description: "Respuesta precisa, formato compacto e iluminacion para setups modernos.",
    whatsappMessage: "Hola, quiero consultar por el Teclado Mecanico K2.",
    specs: ["Switches mecanicos", "Formato compacto", "Conexion USB"],
  },
  {
    id: "mouse-gamer-x1",
    name: "Mouse Gamer X1",
    category: "perifericos",
    categoryLabel: "Perifericos",
    price: 95000,
    image: "/images/mouse-gamer.webp",
    description: "Agarre comodo, sensor preciso y sensibilidad ajustable para jugar o trabajar.",
    whatsappMessage: "Hola, quiero consultar por el Mouse Gamer X1.",
    specs: ["Sensor optico", "Sensibilidad ajustable", "Diseno ergonomico"],
  },
  {
    id: "parlante-bt-p1",
    name: "Parlante Bluetooth P1",
    category: "audio",
    categoryLabel: "Audio",
    price: 210000,
    image: "/images/parlante.webp",
    description: "Audio potente en formato portatil para reuniones, oficina o viajes.",
    whatsappMessage: "Hola, quiero consultar por el Parlante Bluetooth P1.",
    specs: ["Conexion Bluetooth", "Bateria recargable", "Formato portatil"],
  },
  {
    id: "power-bank-20000",
    name: "Power Bank 20000 mAh",
    category: "cargadores",
    categoryLabel: "Cargadores",
    price: 245000,
    image: "/images/power-bank-20000.jpg",
    description: "Bateria portatil de alta capacidad para cargar celular, auriculares y accesorios.",
    whatsappMessage: "Hola, quiero consultar por el Power Bank 20000 mAh.",
    specs: ["20000 mAh", "USB-C y USB-A", "Carga rapida"],
  },
  {
    id: "cargador-usb-c-gan-65w",
    name: "Cargador USB-C GaN 65W",
    category: "cargadores",
    categoryLabel: "Cargadores",
    price: 185000,
    image: "/images/cargador-usb-c-gan.jpg",
    description: "Cargador compacto para celulares, tablets y notebooks compatibles con USB-C.",
    whatsappMessage: "Hola, quiero consultar por el Cargador USB-C GaN 65W.",
    specs: ["Potencia 65W", "Tecnologia GaN", "Proteccion contra sobrecarga"],
  },
  {
    id: "galaxy-tab-a9-plus",
    name: "Samsung Galaxy Tab A9+",
    category: "tablets",
    categoryLabel: "Tablets",
    price: 2190000,
    image: "/images/tablet-galaxy-tab.jpg",
    description: "Tablet con pantalla amplia para entretenimiento, lectura y productividad ligera.",
    whatsappMessage: "Hola, quiero consultar por la Samsung Galaxy Tab A9+.",
    specs: ["Pantalla 11 pulgadas", "Sonido estereo", "Wi-Fi rapido"],
  },
];

// Convierte un numero en precio con formato paraguayo.
export const formatPrice = (price) => "Gs. " + new Intl.NumberFormat("es-PY").format(price);
